spring:
  application:
    name: gateway
  cloud:
    compatibility-verifier:
      enabled: false
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
        wiretap: true   # Enable detailed HTTP client logs for debugging
        pool:
          max-connections: 500
          max-idle-time: 30s
      filter:
        weight-calculator:
          enabled: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        # AGF2 Sample WebApp DIT Special Route - Public access
        - id: agf2-sample-webapp-dit-special-route
          uri: https://ca-java-agf.bluedesert-0d665001.canadacentral.azurecontainerapps.io
          predicates:
            - Host=webdev.agf.com
            - Path=/testdit/pub/**
            - Method=GET
          filters:
            - StripPrefix=1
            - SecureHeaders
            - RewritePath=/pub/(?<segment>.*),/public/${segment}
          order: 1

        # AGF2 Sample WebApp DIT NO Route - Static response
        - id: agf2-sample-webapp-dit-no-route
          uri: no://op
          predicates:
            - Host=webdev.agf.com
            - Path=/testdit/public/200
            - Method=GET
          filters:
            - SecureHeaders
            - SetStatus=200
          order: 2

        # AGF2 Sample WebApp DIT Redirect Route
        - id: agf2-sample-webapp-dit-redirect-route
          uri: no://op
          predicates:
            - Host=webdev.agf.com
            - Path=/testdit/public/302
            - Method=GET
          filters:
            - SecureHeaders
            - name: RedirectTo
              args:
                status: 302
                url: /testdit/public/cms/index.html
          order: 3

        # AGF2 Sample WebApp DIT Main Route
        - id: agf2-sample-webapp-dit-main-route
          uri: https://ca-java-agf.bluedesert-0d665001.canadacentral.azurecontainerapps.io
          predicates:
            - Host=webdev.agf.com
            - Path=/testdit/**
          filters:
            - StripPrefix=1
            - SecureHeaders
            - name: CircuitBreaker
              args:
                name: ditSample500CircuitBreaker
                fallbackUri: forward:/gwerrors/agf/error.html
          order: 9000

        #  Test Route without Host predicate (for direct testing)
        - id: agf2-sample-webapp-dit-test-route
          uri: https://ca-java-agf.bluedesert-0d665001.canadacentral.azurecontainerapps.io
          predicates:
            - Path=/testdit/**
          filters:
            - StripPrefix=1
            - SecureHeaders
          order: 10000

        # Fallback error handling route
        - id: fallback-error-route
          uri: https://webdeverror.agf.com
          predicates:
            - Path=/gwerrors/**
            - Method=POST,GET
          filters:
            - StripPrefix=1
            - name: AddResponseHeader
              args:
                name: X-Fallback-Source
                value: gateway-circuit-breaker
          order: 9400

# Server configuration for Azure Container Apps
server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always

# Management endpoints (same port as main app for ACA)
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,circuitbreakers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  server:
    port: 8080   # same as main server for container app

# Circuit breaker configuration with Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      ditSample500CircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 5s
  retry:
    instances:
      agf2-sample-retry:
        maxAttempts: 3
        waitDuration: 1s
        exponentialBackoffMultiplier: 2

# Logging configuration optimized for Azure Container Apps
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    io.netty: INFO
    agf.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

# Azure Container Apps specific configuration
azure:
  containerapp:
    environment: "canadacentral"
    agf2-sample-webapp:
      url: "https://ca-java-agf.bluedesert-0d665001.canadacentral.azurecontainerapps.io"
      host: "webdev.agf.com"
